var staticTemplate = {
	
	home:{
		staticFeedTemplate:function(){
			var html = '<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.deshow.net/d/file/animal/2009-05/animal-pictures-pet-photography-557-4.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">incident alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/text" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Text</div>'
											+'</div>'
									+'</a>'
									+'<a href="/photos" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'
												+'<div class="feed-menu-text bold">Photos</div>'
											+'</div>'
									+'</a>'
									+'<a href="/voice" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Voice</div>'
											+'</div>'
									+'</a>'
								+'</div>'							
							+'</div>'
						+'</div>'					
					+'</div>'
					
					
					+'<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.wallpaper-valley.com/animal/animal_13.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">incident alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/changecoverage" class="snap feed-addRemove-block inline-block v-align-mid f-sz-14 opensans-regular f-color-green changeCoverage p-relative" data-type="changeCoverage">'
										+'<div class="t-center">'
											+'<div class="sprite-im inline-block v-align-mid message-green-icon">&nbsp;</div>'
											+'<span class="feed-addRemove-text inline-block v-align-mid t-caps">Add / change coverage on home</span>'
										+'</div>'
									+'</a>'
								+'</div>'						
							+'</div>'
						+'</div>'					
					+'</div>';	
					
					
					
						
			return html;
		},
		
		staticPoliciesFeedTemplate:function(){
			var html = '<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.deshow.net/d/file/animal/2009-05/animal-pictures-pet-photography-557-4.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">policy alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/text" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Text</div>'
											+'</div>'
									+'</a>'
									+'<a href="/photos" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'
												+'<div class="feed-menu-text bold">Photos</div>'
											+'</div>'
									+'</a>'
									+'<a href="/voice" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Voice</div>'
											+'</div>'
									+'</a>'
								+'</div>'							
							+'</div>'
						+'</div>'					
					+'</div>';						
			return html;
		},		
		
		editAgencyPicTemplate:function(){
			var html= '<h2 class="t-left f-color-green opensans-regular p-relative agency-prof-overlay-header" style="">'
							+'<span>Agency Profile</span>'
							+'<a href="/manageAgency" class="f-color-red snap p-absolute manageAgency f-sz-14 opensans-regular f-italic">Manage Agency</a>'
						+'</h2>'
                               +'<div class="o-sub-content p-relative">'
									+'<div class="carriers-left-content left ">'
                                        +'<div class="profile-pic-content p-relative t-center">'
											+'<div class="t-center">'
												+'<div class="sprite-im p-relative profile-pic-icon">&nbsp</div>'
												+'<div class="p-absolute agency-pic-text t-upper f-sz-14 text-color-overlay">Agency Logo</div>'
											+'</div>'
                                       +'</div>'
                                    +'</div>'
                                    +'<div class="carriers-right-content left">'
										+'<form>'
											+'<div class="c-agency-logo">'
												+'<input type="file" class="txt-agency-logo-name opensans-regular f-sz-14">'
											+'</div>'
											+'<div class="c-agency-name">'
												+'<input type="text" class="txt-agency-name opensans-regular f-sz-14 f-italic text-color-overlay" value="Auto care">'
											+'</div>'
											+'<div class="c-agency-emailid">'
											   +'<input type="text" class="txt-agency-emailid opensans-regular f-sz-14"  value="autocare@gmail.com">'
											+'</div>'
										+'</form>'
                                    +'</div>'
                                +'</div>'
                                +'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Save</div>';			
			return html;
			
		},
		matchReleaseClaimTemplate:function(){
			var html = '<h2 class="t-left opensans-regular f-color-green" style="display:none;">Header</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="alert-mess-text f-sz-14 t-center opensans-regular bold">The claim has been released to the carrier!</div>'
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="closeOverlay">Done</div>'
							+'</div>';
			return html;
		
		},
		
		shareWithRepTemplate:function(){
			var html = '<h2 class="t-left f-color-green opensans-regular" style="">Share with Representatives</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="text-box-outer textBox-placeholder-italic">'
									+'<input type="search" class="opensans-regular" placeholder="Search.." />'
								+'</div>'
								+'<div class="range-box clr-fl">'
									+'<div class="opensans-regular f-sz-14 range-color left f-italic range-title">Select Range</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel1">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel2">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
								+'</div>'
								+'<div class="rep-block">'
									+'<div class="rep-title-blk clr-fl">'
										+'<div class="name-title opensans-regular t-upper left text-color-overlay bold">names</div>'
										+'<div class="name-title opensans-regular t-upper right text-color-overlay bold">city,state</div>'
									+'</div>'
									+'<div class="rep-content-blk">'
										+'<form>'
                                            +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
											 +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
                                        '</form>'
									+'</div>'
								+'</div>'	
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Assign</div>'
							+'</div>';
			return html;			
		},
		
		/*Added by Naveen - Start */
		showPhotsOverlayTemplate:function(){
			var html ='<div class="o-sub-content p-relative">'
					+'<div class="clr-fl">'
						+'<div style="width:30%;float:left;">'
							+'<ul style="list-style:none;padding:0px;" id="thumbNailImages">'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage1.png" style="width: 100px; height: 100px" /></a></li>'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage2.png" style="width: 100px; height: 100px" /></a></li>'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage3.png" style="width: 100px; height: 100px" /></a></li>'
							+'</ul>'
						+'</div>'
						+'<div id="slider-vertical" style="float:left;position: absolute;height: 312px;left: 123px;top: 10px;">'
						+'</div>'
						+'<div style="width:70%;float:left;border-bottom: 1px solid #b9b8b8;padding:10px 0px;">'
							+'<span class="spanCLassElement t-left f-color-green opensans-regular" style="margin:0px">Accident Image</span><span class="spanCLassElement f-italic" style="margin:0px;color:#939393;font-size:11px">,New jersy</span>'
							+'<img src="images/saveImage.png" style="width:20px;height:20px;position: absolute;right: 170px;"/>'
							+'<img src="images/printImage.png" style="width:20px;height:20px;position: absolute;right: 135px;"/>'
							+'<a href="javascript:void(0)" class="overalyPhots previous" data-type="previous" style="position: absolute;top: 150px;left: 176px;"><img src="images/backwardArrow.png" /></a>'
							+'<div id="viewingImage"></div>'
							+'<a href="javascript:void(0)" class="overalyPhots next" data-type="next" style="position: absolute;top: 150px;right: 35px;"><img src="images/frontArrow.png" /></a>'
						+'</div>'
					+'</div>';
			return html;			
		},
		/*Added by Naveen - End */
		
		assignToRepTemplate:function(){
			var html = '<h2 class="t-left f-color-green opensans-regular" style="">Assign to Representatives</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="text-box-outer textBox-placeholder-italic">'
									+'<input type="search" class="opensans-regular" placeholder="Search.." />'
								+'</div>'
								+'<div class="range-box clr-fl">'
									+'<div class="opensans-regular f-sz-14 range-color left f-italic range-title">Select Range</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel1">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel2">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
								+'</div>'
								+'<div class="rep-block">'
									+'<div class="rep-title-blk clr-fl">'
										+'<div class="name-title opensans-regular t-upper left text-color-overlay bold">names</div>'
										+'<div class="name-title opensans-regular t-upper right text-color-overlay bold">city,state</div>'
									+'</div>'
									+'<div class="rep-content-blk">'
										+'<form>'
                                            +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
											 +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
                                        '</form>'
									+'</div>'
								+'</div>'	
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Assign</div>'
							+'</div>';
			return html;			
		},
		
	
		staticFeedViewTemplate:function(){
			var html = '<div class="view-feed-block">'
						+'<div class="view-in-blocks inline-block v-align-mid bg-color-dblue p-relative">'
							+'<div class="p-relative">'
								+'<div class="feed-user-top-details">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box border-all">'
											+'<img src="http://www.wallpaper-valley.com/animal/animal_13.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									
									+'<div class="feed-user-details-top inline-block v-align-mid">'
										+'<div class="line1">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps bold">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
										+'</div>'
										+'<div class="line1">'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-name t-caps">Male</div>'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'										
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-bday t-upper">19/05/1985</div>'
										+'</div>'
										+'<div class="feed-user-other-details">'
											+'<div class="p-relative inline-block v-align-bot">'
													+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'								
										+'</div>'									
									+'</div>'							
								+'</div>'
								+'<div class="feed-user-bottom-details">'
									+'<div class="inline-block v-align-mid">'
										+'<a href="/share" class="snap feed-btn bg-color-green block f-sz-14 opensans-regular f-color-w share p-relative t-center" data-type="share">'
											+'<div class="t-center mid-align">'
												+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
												+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
											+'</div>'
										+'</a>'
										+'<div class="bg-color-green block feed-btn f-sz-14 opensans-regular f-color-w p-relative t-center alert-type-box">Incident Alert'											
										+'</div>'
									+'</div>'

									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/text" class="snap feed-doc-btn block f-sz-14 opensans-regular textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="feed-menu-text inline-block f-color-green">Files</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/photos" class="snap feed-doc-btn block f-sz-14 opensans-regular photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'											
												+'<div class="feed-menu-text inline-block f-color-green">Photos</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/voice" class="snap feed-doc-btn block f-sz-14 opensans-regular voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'							
												+'<div class="feed-menu-text inline-block f-color-green">Voice</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid">'
										+'<a href="/changecoverage" class="snap feed-doc-btn block f-sz-17 opensans-regular f-color-green changeCoverage p-relative" data-type="changeCoverage">'
											+'<div class="t-center p-relative">'
												+'<div class="sprite-im message-green-icon center-icon">&nbsp;</div>'									
											+'</div>'
											+'<div class="feed-addRemove-text t-center p-relative t-caps">Add / change coverage on home</div>'
										+'</a>'
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="view-in-blocks inline-block v-align-mid bg-color-dblue p-relative">'
							+'<div class="p-relative policy-main-blk">'
								+'<div class="insurance-policy-blk">'
										+'<div class="policy-det-blk inline-block  v-align-mid">'
											+'<input type="checkbox" id="policy1" name="" class="checkbox" />'
											+'<label for="policy1" class="policy-label">'
												+'<div class="p-relative insurance-main-det inline-block v-align-top">'
													+'<div class="insurance-tit-blk">'
														+'<div class="f-sz-16 inline-block opensans-regular">Ideal Insurance,</div>'
														+'<div class="f-sz-13	inline-block opensans-regular">#454723</div>'
													+'</div>'
													+'<div class="insurance-det-blk">'
														+'<ul class="ins-sub-det-group f-sz-12 opensans-regular">'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Due Amount">Due Amount</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">$244</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Next Due Date">Next Due Date</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Oct 25, 2026</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Policy Type">Policy Type</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Property</span>'
															+'</li>'
													+'</div>'
												+'</div>'
											+'</label>'
										+'</div>'
										+'<div class="policy-btn-blk inline-block p-relative v-align-mid">'
											+'<div class="p-relative f-sz-12 opensans-regular t-center">'
												+'<div class="date-blk p-relative">'
													+'<span class="bold">Sep 24,2014</span>'
													+'<span>to</span>'
													+'<span class="bold">Oct 25,2026</span>'
												+'</div>'
												+'<div class="match-blk p-relative">'
													+'<a href="/matchReleaseClaim" class="snap bg-color-green block f-sz-12 ptsans-light t-upper t-center matchReleaseClaim p-relative f-color-w" data-type="matchReleaseClaim">'
														+'<div>Match & Release Claim</div>'
													+'</a>'
												+'</div>'
											+'</div>'
										+'</div>'
								+'</div>'
								+'<div class="insurance-policy-blk">'
										+'<div class="policy-det-blk inline-block  v-align-mid">'
											+'<input type="checkbox" id="policy2" name="" class="checkbox" />'
											+'<label for="policy2" class="policy-label">'
												+'<div class="p-relative insurance-main-det inline-block v-align-top">'
													+'<div class="insurance-tit-blk">'
														+'<div class="f-sz-16 inline-block opensans-regular">Ideal Insurance,</div>'
														+'<div class="f-sz-13	inline-block opensans-regular">#454723</div>'
													+'</div>'
													+'<div class="insurance-det-blk">'
														+'<ul class="ins-sub-det-group f-sz-12 opensans-regular">'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Due Amount">Due Amount</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">$244</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Next Due Date">Next Due Date</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Oct 25, 2026</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Policy Type">Policy Type</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Property</span>'
															+'</li>'
													+'</div>'
												+'</div>'
											+'</label>'
										+'</div>'
										+'<div class="policy-btn-blk inline-block p-relative v-align-mid">'
											+'<div class="p-relative f-sz-12 opensans-regular t-center">'
												+'<div class="date-blk p-relative">'
													+'<span class="bold">Sep 24,2014</span>'
													+'<span>to</span>'
													+'<span class="bold">Oct 25,2026</span>'
												+'</div>'
												+'<div class="match-blk p-relative">'
													+'<a href="/matchReleaseClaim" class="snap bg-color-green block f-sz-12 ptsans-light t-upper t-center matchReleaseClaim p-relative f-color-w" data-type="matchReleaseClaim">'
														+'<div>Match & Release Claim</div>	'			
													+'</a>'
												+'</div>'											
											+'</div>'
										+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="related-feeds p-relative">'
							+'<div class="rel-feeds-title border-bot text-color-overlay">'
								+'<div class="f-sz-14 opensans-regular t-upper">Related Feeds</div>'
							+'</div>'
							+'<div class="rel-feeds-content">'
							+'</div>'
						+'</div>'
						
					+'</div>';
					
			return html;		
		}
	},
	carriers:{
		staticCarrierTemplate:function(){
			var html = '<div class="carrier-home-parent p-relative"><div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular"><div class="carrier-name t-caps t-center">way to safe</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-red  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular"><div class="carrier-name t-caps t-center">health plus</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">auto owners insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">safe co insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">IEE master corp</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">auto owner insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">way to safe</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div></div>';
			return html;
		},
		staticCarrierFeedViewTemplate:function(){
		var html ='<div class="carrier-view-parent bg-color-white p-relative"><div class="carrier-view-leftbloack inline-block v-align-mid p-relative"><div class="carrier-view-auth  opensans-regular p-relative">'
		+'<div class="carrier-view-name inline-block t-caps">agency id</div><div class="carrier-view-id  inline-block">#HP092 542</div></div><div class="carrier-logo-view p-relative">'
		+'<div class="carrierlogo-viewpic"><img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div>'
		+'<div class="carrier-view-social p-relative"><div class="carrier-view-website p-relative  inline-block left bg-color-green  t-caps t-center opensans-regular f-color-w">'
		+'<div class="carrier-website-name t-caps">website</div></div><div class="carrier-view-facebook p-relative inline-block left bg-color-green  t-caps t-center opensans-regular f-color-w">'
		+'<div class="carrier-facebook-icon  "></div><div class="carrier-facebook-name t-caps">facebook</div></div></div></div><div class="carrier-view-rightblock inline-block v-align-mid p-relative ">'
		+'<div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"><div class="carrier-view-left p-relative left"><div class="carrier-left-width t-caps opensans-regular clr-fl">'
		+'<div class="carrier-left-title t-right left">agency name</div><div class="carrier-left-content t-left right ">way to safe</div></div></div><div class="carrier-view-right right t-caps opensans-regular">'
		+'<div class="carrier-left-width clr-fl"><div class="carrier-left-title t-right left">address</div><div class="carrier-left-content t-left right">westere parkway</div></div></div></div></div>'
		+'<div class="carrier-view-block p-relative "><div class="carrier-border-view clr-fl border-bot"><div class="carrier-view-left p-relative left"><div class="carrier-left-width t-caps opensans-regular clr-fl">'
		+'<div class="carrier-left-title t-right left">address</div><div class="carrier-left-content t-left right ">san francisco</div></div></div><div class="carrier-view-right right t-caps opensans-regular">'
		+'<div class="carrier-left-width clr-fl"><div class="carrier-left-title t-right left">state</div><div class="carrier-left-content t-left right">us</div></div></div></div>'
		+'<div class="carrier-view-block p-relative "><div class="carrier-border-view clr-fl border-bot"><div class="carrier-view-left p-relative left"><div class="carrier-left-width t-caps opensans-regular clr-fl">'
		+'<div class="carrier-left-title t-right left">city</div><div class="carrier-left-content t-left right ">san francisco</div></div></div><div class="carrier-view-right right t-caps opensans-regular">'
		+'<div class="carrier-left-width clr-fl"><div class="carrier-left-title t-right left">phone</div><div class="carrier-left-content t-left right">(914)000 000 00</div></div></div></div></div>'
		+' <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl"><div class="carrier-view-left p-relative left"><div class="carrier-left-width t-caps opensans-regular clr-fl">'
		+'<div class="carrier-left-title t-right left">zip</div><div class="carrier-left-content t-left right ">9401</div></div></div><div class="carrier-view-right right t-caps opensans-regular">'
		+'<div class="carrier-left-width clr-fl"><div class="carrier-left-title t-right left">email</div><div class="carrier-left-content t-left right">waytosafe@mail.com</div></div></div></div></div></div>';
		return html;
	}
		
	},
	
	customers:{
		staticCustomerTemplate:function(){
			var html = '<div class="customer-home-parent clr-fl p-relative"><div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">James jeo</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-red  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w">View</div></div>'
			+'</div>';
			return html;
		}		
		
	},
	myreps:{
		inviteRepsTemplate:function(){
			var html = '<h2 class="t-left f-color-green opensans-regular" style="">Invite Reps</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="f-sz-14 t-left opensans-regular invite-reps-text">User will have access to all the features of Dashboard</div>'
								+'<div class="text-box-outer">'
									+'<input type="text" class="opensans-regular" placeholder="Mail Address" />'
								+'</div>'
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Done</div>'
							+'</div>';
			return html;
		
		}
	
	}
	
};
