var staticTemplate = {
	
	home:{
		staticFeedTemplate:function(){
			var html = '<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.deshow.net/d/file/animal/2009-05/animal-pictures-pet-photography-557-4.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">incident alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/text" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Text</div>'
											+'</div>'
									+'</a>'
									+'<a href="/photos" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'
												+'<div class="feed-menu-text bold">Photos</div>'
											+'</div>'
									+'</a>'
									+'<a href="/voice" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Voice</div>'
											+'</div>'
									+'</a>'
								+'</div>'							
							+'</div>'
						+'</div>'					
					+'</div>'
					
					
					+'<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.wallpaper-valley.com/animal/animal_13.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">incident alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/changecoverage" class="snap feed-addRemove-block inline-block v-align-mid f-sz-14 opensans-regular f-color-green changeCoverage p-relative" data-type="changeCoverage">'
										+'<div class="t-center">'
											+'<div class="sprite-im inline-block v-align-mid message-green-icon">&nbsp;</div>'
											+'<span class="feed-addRemove-text inline-block v-align-mid t-caps">Add / change coverage on home</span>'
										+'</div>'
									+'</a>'
								+'</div>'						
							+'</div>'
						+'</div>'					
					+'</div>';	
					
					
					
						
			return html;
		},
		
		staticPoliciesFeedTemplate:function(){
			var html = '<div class="feed-block clr-fl">'
						+'<div class="lf-block left">'
						+'<div class="leftblk-spacing">'
							+'<div class="feed-det bg-color-dblue p-relative">'						
								+'<div class="feed-det-pad p-relative">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box">'
											+'<img src="http://www.deshow.net/d/file/animal/2009-05/animal-pictures-pet-photography-557-4.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									+'<div class="feed-user-det-b inline-block v-align-mid">'
										+'<div class="top-b p-relative">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">policy alert</div>'
											+'<div class="p-relative inline-block v-align-mid">'
												+'<div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div>'
										+'</div>'
										+'<div class="bot-b">'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'
										+'</div>'
									+'</div>'		
									+'<div class="feed-user-share-b inline-block v-align-mid">'
										+'<div class="myshare">'
											+'<div class="inner-share-spacing snap" data-type="share">'
												+'<div class="t-center mid-align">'
													+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
													+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
												+'</div>'
											+'</div>'
										+'</div>'									
										+'<div class="myview">'
											+'<div class="inner-view-spacing snap" data-type="view">'
												+'<div class="t-center mid-align">'
														+'<div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div>'
														+'<span class="feed-menu-text inline-block v-align-mid f-color-w">View</span>'
												+'</div>'
											+'</div>'
										+'</div>'								
									+'</div>'								
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="rg-block left p-relative">'
							+'<div class="feed-det bg-color-dblue p-relative">'
								+'<div class="feed-docs-pad p-relative docs-block t-center">'
									+'<a href="/text" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Text</div>'
											+'</div>'
									+'</a>'
									+'<a href="/photos" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'
												+'<div class="feed-menu-text bold">Photos</div>'
											+'</div>'
									+'</a>'
									+'<a href="/voice" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative">'
												+'<div class="doc-icon-box" >'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span></div>'	
												+'<div class="feed-menu-text bold">Voice</div>'
											+'</div>'
									+'</a>'
								+'</div>'							
							+'</div>'
						+'</div>'					
					+'</div>';						
			return html;
		},

		staticArchiveFeedTemplate:function(){
			var html= '<div class="feed-block clr-fl"> <div class="lf-block left"> <div class="leftblk-spacing"> <div class="feed-det bg-color-dblue p-relative"> <div class="feed-det-pad p-relative"> <div class="feed-pic-b inline-block v-align-mid"> <div id="" class="feed-user-pic-box"> <input type="checkbox" id="feedcheck" name="" class="checkbox"><label for="feedcheck" class="feed-label"></label> <img src="http://www.deshow.net/d/file/animal/2009-05/animal-pictures-pet-photography-557-4.jpg" alt="" class="feeduserpic"> </div></div><div class="feed-user-det-b inline-block v-align-mid"> <div class="top-b p-relative"> <div class="p-relative inline-block v-align-top"> <div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps">Hugh Jackman</div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-13 alert-color alert-type t-caps">policy alert</div><div class="p-relative inline-block v-align-mid"> <div class="sprite-im rep-icon rep-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 rep-name t-caps">robert</div></div><div class="bot-b"> <div class="p-relative inline-block v-align-bot"> <div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div><div class="p-relative inline-block v-align-bot"> <div class="sprite-im map-icon map-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div><div class="p-relative inline-block v-align-bot"> <div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div><div class="p-relative inline-block v-align-bot"> <div class="sprite-im email-icon email-icon-pos">&nbsp;</div></div><div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div></div></div><div class="feed-user-share-b inline-block v-align-mid"> <div class="myshare"> <div class="inner-share-spacing snap" data-type="share"> <div class="t-center mid-align"> <div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div><span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span> </div></div></div><div class="myview"> <div class="inner-view-spacing snap" data-type="view"> <div class="t-center mid-align"> <div class="sprite-im inline-block v-align-mid view-icon">&nbsp;</div><span class="feed-menu-text inline-block v-align-mid f-color-w">View</span> </div></div></div></div></div></div></div></div><div class="rg-block left p-relative"> <div class="feed-det bg-color-dblue p-relative"> <div class="feed-docs-pad p-relative docs-block t-center"> <a href="/text" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green textDoc p-relative" data-type="textDoc"> <div class="t-center p-relative"> <div class="doc-icon-box"> <div class="sprite-im text-icon doc-icon-placement">&nbsp;</div></div><div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span> </div><div class="feed-menu-text bold">Text</div></div></a> <a href="/photos" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green photosDoc p-relative" data-type="photosDoc"> <div class="t-center p-relative"> <div class="doc-icon-box"> <div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div></div><div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span> </div><div class="feed-menu-text bold">Photos</div></div></a> <a href="/voice" class="snap feed-docs inline-block v-align-mid f-sz-14 opensans-regular f-color-green voiceDoc p-relative" data-type="voiceDoc"> <div class="t-center p-relative"> <div class="doc-icon-box"> <div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div></div><div class="doc-cnt-box"><span class="doc-count doc-count-placement">2</span> </div><div class="feed-menu-text bold">Voice</div></div></a> </div></div></div></div>';
			return html;
		},		
		
		
		matchReleaseClaimTemplate:function(){
			var html = '<h2 class="t-left opensans-regular f-color-green" style="display:none;">Header</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="alert-mess-text f-sz-14 t-center opensans-regular bold">The claim has been released to the carrier!</div>'
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="closeOverlay">Done</div>'
							+'</div>';
			return html;
		
		},
		
		 editAgencyPicTemplate: function () {
            var html = '<div class="header-panel border-bot"> <div class="left-content-panel t-left left f-color-green f-sz-18 opensans-regular">'
                    + 'Agency Profile</div> <div class="right-content-panel t-right right f-color-red f-sz-12 opensans-regular"> <i>Manage Agency</i></div>'
                    + '</div> <div class="o-sub-content p-relative"> <div class="carriers-left-content left "> <div class="profile-pic-content"> '
                    + '<div id="id-agency-logo" class="agency-logo p-relative"> <img src="images/Logo.png" alt="" id="id-agencyprofilelogo" class="agencyprofilelogo"> '
                    + '</div> </div> </div> <div class="carriers-right-content left "> <div class="c-agency-logo"> '
                    + '<input type="text" id="id-agency-logo-name" class="txt-agency-logo-name opensans-regular f-sz-14" value="Agency Logo.jpg" disabled> '
                    + '<input type="file" style="display:none;" id="inputfile" onchange="readURL(this)" /> '
                    + '<div class="browse-button-content p-absolute f-color-w f-sz-16 opensans-regular" onclick="javascript:document.getElementById(\'inputfile\').click();"> Browse </div>'
                    + '</div> <div class="c-agency-name"> <input type="text" class="txt-agency-name opensans-regular f-sz-14" value="John Doe"> </div>'
                    + '<div class="c-agency-emailid"> <input type="text" class="txt-agency-emailid opensans-regular f-sz-14" value="johndoe@gmail.com"> </div> </div>'
                    + '</div> <div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Save</div>';

            return html;

        },
        pushMessageTemplate: function () {
            var html = ' <h2 class="t-left f-color-green opensans-regular" style="">Push Message</h2> <div class="o-sub-content p-relative"> <div class="c-textarea text-box-outer textBox-placeholder-italic"> <textarea draggable="false" class="textarea opensans-regular" placeholder="Type message" maxlength="170"></textarea> </div> <div class="delivery-box clr-fl"> <div class="delivery-time left opensans-regular">Delivery Time</div> <div class="deliverytime-content left opensans-regular clr-fl"> <div class="now left">Now</div> <div class="later left">Later</div> </div> </div> <div class="later-box clr-fl"> <div class="select-date-content left opensans-regular"> <div class="select-date left opensans-regular">Select Date</div> <div class="text-box-outer textBox-placeholder-italic left push-select-dropdown border-all p-relative"> <input type="text" class="none-1 opensans-regular left" placeholder="22-11-2014" /> <div class="sprite-im datepicker-icon p-absolute"></div> </div> </div> <div class="time-content left opensans-regular clr-fl"> <div class="time left opensans-regular">Time</div> <div class="text-box-outer textBox-placeholder-italic left time-dropdown-1 border-all p-relative"> <input type="text" class="none-1 opensans-regular left" placeholder="10.55" /> <div class="sprite-im drop-down-icon push-drop-down-icon-1 p-absolute"></div> </div> <div class="text-box-outer textBox-placeholder-italic left time-dropdown-2 border-all p-relative"> <input type="text" class="none-1 opensans-regular left" placeholder="AM" /> <div class="sprite-im drop-down-icon push-drop-down-icon-2 p-absolute"></div> </div> <!-- <div class="time-dropdown left opensans-regular p-relative">10.55<div class="sprite-im push-drop-down-icon-1 dropdown-icon p-absolute"></div></div> <div class="am-pm-dropdowm left opensans-regular">AM<div class="sprite-im push-drop-down-icon-2 drop-down-icon dropdown-icon p-absolute"></div></div>--> </div> </div> <div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Send</div> </div> ';

            return html;

        },
        privacyTemplate: function () {
            var html = '<h2 class="t-center f-color-green opensans-regular" style="">Privacy</h2> <div class="o-sub-content p-relative"> <h3 class="enable-text t-center f-sz-14 opensans-regular "><b>Enable / disable privacy option for your agency</b></h3> <h3 class="enable-text t-left f-sz-14 opensans-regular ">Make all profile public</h3> <h3 class="enable-text t-left f-sz-14 opensans-regular ">Make all profile private</h3> <h3 class="enable-text t-left f-sz-14 opensans-regular ">Custom</h3> <div class="text-box-outer textBox-placeholder-italic border-all"> <input type="search" class="opensans-regular" placeholder="Search.." /> </div> <div class="rep-block"> <div class="rep-title-blk clr-fl"> <div class="name-title opensans-regular t-upper left text-color-overlay bold">Member Names</div> <div class="nameRepId opensans-regular t-upper left text-color-overlay bold">Rep ID</div> <div class="name-title opensans-regular t-upper right text-color-overlay bold">Private / Public</div> </div> <div class="rep-content-blk"> <form> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class="rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="nameRepId f-sz-14 text-color-overlay left"><i>#5454547</i></div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class="rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="nameRepId f-sz-14 text-color-overlay left"><i>#5454547</i></div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class="rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="nameRepId f-sz-14 text-color-overlay left"><i>#5454547</i></div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class="rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="nameRepId f-sz-14 text-color-overlay left"><i>#5454547</i></div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class="rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="nameRepId f-sz-14 text-color-overlay left"><i>#5454547</i></div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> </form> </div> </div> <div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Send</div> </div>';

            return html;

        },
       
		
		/*Added by Naveen - Start */
		showPhotsOverlayTemplate:function(){
			var html ='<div class="o-sub-content p-relative">'
					+'<div class="clr-fl">'
						+'<div style="width:30%;float:left;">'
							+'<ul style="list-style:none;padding:0px;" id="thumbNailImages">'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage1.png" style="width: 100px; height: 100px" /></a></li>'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage2.png" style="width: 100px; height: 100px" /></a></li>'
								+'<li><a href="javascript:void(0)" class="overalyPhots" data-type="thumbNail"><img src="images/carDamage3.png" style="width: 100px; height: 100px" /></a></li>'
							+'</ul>'
						+'</div>'
						+'<div id="slider-vertical" style="float:left;position: absolute;height: 312px;left: 123px;top: 10px;">'
						+'</div>'
						+'<div style="width:70%;float:left;border-bottom: 1px solid #b9b8b8;padding:10px 0px;">'
							+'<span class="spanCLassElement t-left f-color-green opensans-regular" style="margin:0px">Accident Image</span><span class="spanCLassElement f-italic" style="margin:0px;color:#939393;font-size:11px">,New jersy</span>'
							+'<img src="images/saveImage.png" style="width:20px;height:20px;position: absolute;right: 170px;"/>'
							+'<img src="images/printImage.png" style="width:20px;height:20px;position: absolute;right: 135px;"/>'
							+'<a href="javascript:void(0)" class="overalyPhots previous" data-type="previous" style="position: absolute;top: 150px;left: 176px;"><img src="images/backwardArrow.png" /></a>'
							+'<div id="viewingImage"></div>'
							+'<a href="javascript:void(0)" class="overalyPhots next" data-type="next" style="position: absolute;top: 150px;right: 35px;"><img src="images/frontArrow.png" /></a>'
						+'</div>'
					+'</div>';
			return html;			
		},

		shareWithRepTemplate: function () {
            var html = ' <h2 class="t-left f-color-green opensans-regular" style="">Share with Representatives</h2>'
                    + ' <div class="o-sub-content p-relative"> <div class="text-box-outer textBox-placeholder-italic"> <input type="search"'
                    + 'class="opensans-regular" placeholder="Search.." /> </div> <div class="range-box clr-fl"> <div class="opensans-regular'
                    + 'f-sz-14 range-color left f-italic range-title">Select Range</div> <div class="text-box-outer p-relative textBox-placeholder-italic left range-sel1">'
                    + '<input type="text" class="opensans-regular p-relative" placeholder="None" /> '
                    + '<div class="drop-down-icon-1 sprite-im drop-down-icon dropdown-icon p-absolute"></div> </div> <div class="text-box-outer '
                    + 'textBox-placeholder-italic p-relative left range-sel2"> <input type="text" class="opensans-regular p-relative" placeholder="None" /> '
                    + '<div class="drop-down-icon-2 sprite-im drop-down-icon dropdown-icon p-absolute"></div> </div> </div> <div class="rep-block">'
                    + '<div class="rep-title-blk clr-fl"> <div class="name-title opensans-regular t-upper left text-color-overlay bold">NAMES</div>'
                    + '<div class="name-title opensans-regular t-upper right text-color-overlay bold">CITY,STATE</div> </div> <div class="rep-content-blk"> <form> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name1" name="" class="checkbox" /> <label for="name1" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name2" name="" class="checkbox" /> <label for="name2" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name3" name="" class="checkbox" /> <label for="name3" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name4" name="" class="checkbox" /> <label for="name4" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name5" name="" class="checkbox" /> <label for="name5" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> <div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative"> <input type="checkbox" id="name6" name="" class="checkbox" /> <label for="name6" class=" rep-label"> <div class="lbl-in-block p-relative"> <div class="f-sz-14 text-color-overlay left rep-name">Anderson</div> <div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div> </div> </label> </div> </form> </div> </div> <div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Assign</div> </div> ';

            return html;
        },


		/*Added by Naveen - End */
		
		assignToRepTemplate:function(){
			var html = '<h2 class="t-left f-color-green opensans-regular" style="">Assign to Representatives</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="text-box-outer textBox-placeholder-italic">'
									+'<input type="search" class="opensans-regular" placeholder="Search.." />'
								+'</div>'
								+'<div class="range-box clr-fl">'
									+'<div class="opensans-regular f-sz-14 range-color left f-italic range-title">Select Range</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel1">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
									+'<div class="text-box-outer textBox-placeholder-italic left range-sel2">'				
										+'<input type="text" class="opensans-regular" placeholder="None" />'
										+'<div class="sprite-im drop-down-icon dropdown-icon  p-absolute"></div>'
									+'</div>'
								+'</div>'
								+'<div class="rep-block">'
									+'<div class="rep-title-blk clr-fl">'
										+'<div class="name-title opensans-regular t-upper left text-color-overlay bold">names</div>'
										+'<div class="name-title opensans-regular t-upper right text-color-overlay bold">city,state</div>'
									+'</div>'
									+'<div class="rep-content-blk">'
										+'<form>'
                                            +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
											 +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
										    +'<div class="rep-grp-blk opensans-regular border-bot text-color-overlay p-relative">'
                                                +'<input type="checkbox" id="name1" name="" class="checkbox" />'
                                                +'<label for="name1" class="rep-label">'
                                                        +'<div class="lbl-in-block p-relative">'
															+'<div class="f-sz-14 text-color-overlay left rep-name">Anderson</div>'
                                                            +'<div class="t-caps f-sz-13 right f-italic t-right location-color rep-location">NewYork, CA</div>'
                                                        +'</div>'
                                                +'</label>'
                                           +'</div>'
                                        '</form>'
									+'</div>'
								+'</div>'	
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Assign</div>'
							+'</div>';
			return html;			
		},
		
	
		staticFeedViewTemplate:function(){
			var html = '<div class="view-feed-block">'
						+'<div class="view-in-blocks inline-block v-align-mid bg-color-dblue p-relative">'
							+'<div class="p-relative">'
								+'<div class="feed-user-top-details">'
									+'<div class="feed-pic-b inline-block v-align-mid">'
										+'<div id="" class="feed-user-pic-box border-all">'
											+'<img src="http://www.wallpaper-valley.com/animal/animal_13.jpg" alt="" class="feeduserpic">'
										+'</div>'
									+'</div>'
									
									+'<div class="feed-user-details-top inline-block v-align-mid">'
										+'<div class="line1">'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-16 cust-name t-caps bold">Hugh Jackman</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-time t-upper">10.55 AM</div>'
										+'</div>'
										+'<div class="line1">'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-name t-caps">Male</div>'
											+'<div class="p-relative inline-block v-align-top">'
												+'<div class="sprite-im mobile-icon mobile-icon-pos">&nbsp;</div>'
											+'</div>'										
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-bday t-upper">19/05/1985</div>'
										+'</div>'
										+'<div class="feed-user-other-details">'
											+'<div class="p-relative inline-block v-align-bot">'
													+'<div class="sprite-im calendar-icon calendar-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-date t-caps">Nov 18,2014</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im map-icon map-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 feed-location t-caps">California</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im phone-icon phone-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-phone t-caps">0000 000 000</div>'
											+'<div class="p-relative inline-block v-align-bot">'
												+'<div class="sprite-im email-icon email-icon-pos">&nbsp;</div>'
											+'</div>'
											+'<div class="p-relative inline-block opensans-regular v-align-bot f-sz-12 cust-email no-right-margin">xyz@mail.com</div>'								
										+'</div>'									
									+'</div>'							
								+'</div>'
								+'<div class="feed-user-bottom-details">'
									+'<div class="inline-block v-align-mid">'
										+'<a href="/share" class="snap feed-btn bg-color-green block f-sz-14 opensans-regular f-color-w share p-relative t-center" data-type="share">'
											+'<div class="t-center mid-align">'
												+'<div class="sprite-im inline-block v-align-mid share-icon">&nbsp;</div>'
												+'<span class="feed-menu-text inline-block v-align-mid f-color-w">Share</span>'
											+'</div>'
										+'</a>'
										+'<div class="bg-color-green block feed-btn f-sz-14 opensans-regular f-color-w p-relative t-center alert-type-box">Incident Alert'											
										+'</div>'
									+'</div>'

									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/text" class="snap feed-doc-btn block f-sz-14 opensans-regular textDoc p-relative" data-type="textDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im text-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'
												+'<div class="feed-menu-text inline-block f-color-green">Files</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/photos" class="snap feed-doc-btn block f-sz-14 opensans-regular photosDoc p-relative" data-type="photosDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im photos-icon doc-icon-placement">&nbsp;</div>'																								
												+'</div>'											
												+'<div class="feed-menu-text inline-block f-color-green">Photos</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid" style="display:none;">'
										+'<a href="/voice" class="snap feed-doc-btn block f-sz-14 opensans-regular voiceDoc p-relative" data-type="voiceDoc">'
											+'<div class="t-center p-relative bg-color-white f-color-green">'
												+'<div class="doc-icon-box inline-block">'
													+'<div class="sprite-im voice-icon doc-icon-placement">&nbsp;</div>'																									
												+'</div>'							
												+'<div class="feed-menu-text inline-block f-color-green">Voice</div>'
											+'</div>'
											+'<div class="t-center p-relative bg-color-green f-color-w">'
												+'<div class="file-count inline-block">2</div>'
												+'<div class="inline-block">View</div>'
											+'</div>'
										+'</a>'
									+'</div>'
									+'<div class="inline-block v-align-mid">'
										+'<a href="/changecoverage" class="snap feed-doc-btn block f-sz-17 opensans-regular f-color-green changeCoverage p-relative" data-type="changeCoverage">'
											+'<div class="t-center p-relative">'
												+'<div class="sprite-im message-green-icon center-icon">&nbsp;</div>'									
											+'</div>'
											+'<div class="feed-addRemove-text t-center p-relative t-caps">Add / change coverage on home</div>'
										+'</a>'
									+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="view-in-blocks inline-block v-align-mid bg-color-dblue p-relative">'
							+'<div class="p-relative policy-main-blk">'
								+'<div class="insurance-policy-blk">'
										+'<div class="policy-det-blk inline-block  v-align-mid">'
											+'<input type="checkbox" id="policy1" name="" class="checkbox" />'
											+'<label for="policy1" class="policy-label">'
												+'<div class="p-relative insurance-main-det inline-block v-align-top">'
													+'<div class="insurance-tit-blk">'
														+'<div class="f-sz-16 inline-block opensans-regular">Ideal Insurance,</div>'
														+'<div class="f-sz-13	inline-block opensans-regular">#454723</div>'
													+'</div>'
													+'<div class="insurance-det-blk">'
														+'<ul class="ins-sub-det-group f-sz-12 opensans-regular">'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Due Amount">Due Amount</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">$244</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Next Due Date">Next Due Date</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Oct 25, 2026</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Policy Type">Policy Type</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Property</span>'
															+'</li>'
													+'</div>'
												+'</div>'
											+'</label>'
										+'</div>'
										+'<div class="policy-btn-blk inline-block p-relative v-align-mid">'
											+'<div class="p-relative f-sz-12 opensans-regular t-center">'
												+'<div class="date-blk p-relative">'
													+'<span class="bold">Sep 24,2014</span>'
													+'<span>to</span>'
													+'<span class="bold">Oct 25,2026</span>'
												+'</div>'
												+'<div class="match-blk p-relative">'
													+'<a href="/matchReleaseClaim" class="snap bg-color-green block f-sz-12 ptsans-light t-upper t-center matchReleaseClaim p-relative f-color-w" data-type="matchReleaseClaim">'
														+'<div>Match & Release Claim</div>'
													+'</a>'
												+'</div>'
											+'</div>'
										+'</div>'
								+'</div>'
								+'<div class="insurance-policy-blk">'
										+'<div class="policy-det-blk inline-block  v-align-mid">'
											+'<input type="checkbox" id="policy2" name="" class="checkbox" />'
											+'<label for="policy2" class="policy-label">'
												+'<div class="p-relative insurance-main-det inline-block v-align-top">'
													+'<div class="insurance-tit-blk">'
														+'<div class="f-sz-16 inline-block opensans-regular">Ideal Insurance,</div>'
														+'<div class="f-sz-13	inline-block opensans-regular">#454723</div>'
													+'</div>'
													+'<div class="insurance-det-blk">'
														+'<ul class="ins-sub-det-group f-sz-12 opensans-regular">'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Due Amount">Due Amount</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">$244</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Next Due Date">Next Due Date</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Oct 25, 2026</span>'
															+'</li>'
															+'<li class="t-left">'
																+'<span class="f-italic t-left text-ellipsis inline-block v-align-mid ins-sub-head" title="Policy Type">Policy Type</span>'
																+'<span class="inline-block v-align-mid t-center">:</span>'
																+'<span class="t-left inline-block v-align-mid bold">Property</span>'
															+'</li>'
													+'</div>'
												+'</div>'
											+'</label>'
										+'</div>'
										+'<div class="policy-btn-blk inline-block p-relative v-align-mid">'
											+'<div class="p-relative f-sz-12 opensans-regular t-center">'
												+'<div class="date-blk p-relative">'
													+'<span class="bold">Sep 24,2014</span>'
													+'<span>to</span>'
													+'<span class="bold">Oct 25,2026</span>'
												+'</div>'
												+'<div class="match-blk p-relative">'
													+'<a href="/matchReleaseClaim" class="snap bg-color-green block f-sz-12 ptsans-light t-upper t-center matchReleaseClaim p-relative f-color-w" data-type="matchReleaseClaim">'
														+'<div>Match & Release Claim</div>	'			
													+'</a>'
												+'</div>'											
											+'</div>'
										+'</div>'
								+'</div>'
							+'</div>'
						+'</div>'
						+'<div class="related-feeds p-relative">'
							+'<div class="rel-feeds-title border-bot text-color-overlay">'
								+'<div class="f-sz-14 opensans-regular t-upper">Related Feeds</div>'
							+'</div>'
							+'<div class="rel-feeds-content">'
							+'</div>'
						+'</div>'
						
					+'</div>';
					
			return html;		
		}
	},
	// settings:{
		
	// },
		carriers:{
		staticCarrierTemplate:function(){
			var html = '<div class="carrier-home-parent p-relative"><div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular"><div class="carrier-name t-caps t-center">way to safe</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular"><div class="carrier-name t-caps t-center">health plus</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">auto owners insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">safe co insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">IEE master corp</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">auto owner insurance</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div>'
			+'<div class="carrier-profile-screen left border-all p-relative"><div class="carrier-logo p-relative  opensans-regular"><div class="carrierlogo-pic">'
			+'<img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"></div></div><div class="carrier-info bg-color-white p-relative carrier-groupblock  opensans-regular">'
			+'<div class="carrier-name t-caps t-center">way to safe</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div>'
			+'<div class="carrier-view p-relative  bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="viewcarrierfeedview">view</div></div></div></div>';
			return html;
		},
		staticCarrierFeedViewTemplate:function(){
		var html ='<div class="carrier-view-parent bg-color-white p-relative"> <div class="carrier-view-leftbloack inline-block v-align-mid p-relative"> <div class="carrier-view-auth opensans-regular p-relative"> <div class="carrier-view-name inline-block t-caps">carrier id</div> <div class="carrier-view-id inline-block">#HP092 542</div> </div> <div class="carrier-logo-view p-relative"> <div class="carrierlogo-viewpic"> <img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"> </div> </div> <div class="carrier-view-social p-relative clr-fr"> <div class="carrier-view-website p-relative left bg-color-green"> <div class="p-relative inline-block v-align-top"> <div class="sprite-im pop-out">&nbsp;</div> </div> <div class="carrier-website-name inline-block t-caps opensans-regular f-color-w">website</div> </div> <div class="carrier-view-facebook p-relative left bg-color-green"> <div class="p-relative inline-block v-align-top"> <div class="sprite-im pop-out">&nbsp;</div> </div> <div class="carrier-facebook-name inline-block t-caps opensans-regular f-color-w">facebook</div> </div> </div> </div> <div class="carrier-view-rightblock inline-block v-align-mid p-relative "> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">agency name</div> <div class="carrier-left-content t-left right ">way to safe</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">address</div> <div class="carrier-left-content t-left right">westere parkway</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">address</div> <div class="carrier-left-content t-left right ">san francisco</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">state</div> <div class="carrier-left-content t-left right">us</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">city</div> <div class="carrier-left-content t-left right ">san francisco</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">phone</div> <div class="carrier-left-content t-left right">(914)000 000 00</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">zip</div> <div class="carrier-left-content t-left right ">9401</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">email</div> <div class="carrier-left-content t-left right">waytosafe@mail.com</div> </div> </div> </div> </div> </div> </div> <div class="associated-carrierview p-relative"> <div class="p-relative "> <div class="associated-carrier-sort t-upper p-relative opensans-regular inline-block">associated customers</div> <div class="p-relative inline-block"> <div class="sprite-im drop-down-icon">&nbsp;</div> </div> </div> <div class="associated-carrier-feed p-relative border-bot"> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">james jeo</div> <div class="carrier-location t-caps t-center">location</div> </div> </div> </div> </div> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">Hugh jackman</div> <div class="carrier-location t-caps t-center">location</div> </div> </div> </div> </div> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">smith</div> <div class="carrier-location t-caps t-center">location</div> </div> </div> </div> </div> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">anderson</div> <div class="carrier-location t-caps t-center">location</div> </div> </div> </div> </div> </div> </div>';
		return html;
	}
		
	},
	
	customers:{
		staticCustomerTemplate:function(){
			var html = '<div class="customer-home-parent clr-fl p-relative"><div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">James jeo</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w  snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'<div class="customer-feed-screen clr-fl left border-all p-relative"><div class="customer-feed-info clr-fl p-relative">'
			+'<div class="customer-feed-pic left "><img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"></div><div class="customer-profile-info left  opensans-regular f-color-w p-relative">'
			+'<div class="carrier-name t-caps t-center">Mano abram</div>'
			+'<div class="carrier-location  t-caps t-center">location</div><div class="carrier-email t-center">carrier@mail.com</div></div><div class="customer-checkbox left"></div>'
			+'</div><div class="customer-feed-view p-relative bg-color-green  t-caps t-center opensans-regular f-color-w snap" data-type="customerprofileviewfeed">View</div></div>'
			+'</div>';
			return html;
		},
     staticCustomerViewTemplate:function(){
		 var html='<div class="carrier-view-parent bg-color-white p-relative"> <div class="customer-view-feed inline-block v-align-mid p-relative"> <div class="customer-logo-view p-relative"> <div class="customerlogo-viewpic"> <img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"> </div> </div> <div class="customer-view-name opensans-regular t-caps t-center p-relative">richardson</div> </div> <div class="carrier-view-rightblock inline-block v-align-mid p-relative "> <div class="customer-view-block p-relative "> <div class="customer-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">first name</div> <div class="carrier-left-content t-left right ">richardson</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">last name</div> <div class="carrier-left-content t-left right">john</div> <div class="customer-view-mbapp p-relative inline-block v-align-top right"> <div class="sprite-im carrier-mobile-icon">&nbsp;</div> </div> </div> </div> </div> </div> <div class="customer-view-block p-relative "> <div class="customer-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">gender</div> <div class="carrier-left-content t-left right ">male</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">occupation</div> <div class="carrier-left-content t-left right">doctor</div> </div> </div> </div> </div> <div class="customer-view-block p-relative "> <div class="customer-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">year of birth</div> <div class="carrier-left-content t-left right ">12-11-1986</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">residential city</div> <div class="carrier-left-content t-left right">california</div> </div> </div> </div> </div> <div class="customer-view-block p-relative "> <div class="customer-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">residential state</div> <div class="carrier-left-content t-left right t-upper ">us</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">residential zipcode</div> <div class="carrier-left-content t-left right">9401</div> </div> </div> </div> </div> <div class="customer-view-block p-relative "> <div class="customer-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width opensans-regular clr-fl"> <div class="carrier-left-title t-right t-caps left">email</div> <div class="carrier-left-content t-left right">richardson@mail.com</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">phone</div> <div class="carrier-left-content t-left right">(415)914-00000</div> </div> </div> </div> </div> <div class="customer-view-button p-relative"> <div class="customer-view-policy inline-block t-caps t-center opensans-regular">policies</div> <div class="customer-policy-button p-relative inline-block bg-color-red t-caps t-center opensans-regular f-color-w">property policy</div> <div class="customer-policy-button p-relative inline-block bg-color-green t-caps t-center opensans-regular f-color-w">health policy</div> <div class="customer-policy-button p-relative inline-block bg-color-green t-caps t-center opensans-regular f-color-w">vehicle policy</div> </div> </div> </div> <div class="associated-carrierview p-relative"> <div class="p-relative "> <div class="associated-carrier-sort t-upper p-relative opensans-regular inline-block">associated reps</div> <div class="p-relative inline-block"> <div class="sprite-im drop-down-icon">&nbsp;</div> </div> </div> <div class="associated-carrier-feed p-relative border-bot"> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">james jeo</div> <div class="carrier-location t-caps t-center">location</div> <div class="carrier-location t-center">mail@mail.com</div> </div> </div> </div> </div> <div class="carrier-feed-associated-view left p-relative"> <div class="border-all p-relative"> <div class="p-relative"> <div class="associated-carrier-pic inline-block "> <img src="http://johnjournal.bravesites.com/files/images/Profile_Score_Photo.jpg" alt="" class="carrier-img-width"> </div> <div class="associated-cus-info inline-block opensans-regular f-color-w p-relative"> <div class="carrier-name t-caps t-center">robert</div> <div class="carrier-location t-caps t-center">location</div> <div class="carrier-location t-center">mail@mail.com</div> </div> </div> </div> </div></div>';
		 return html;
	 },		
	 staticSettingsTemplate:function(){
			var html ='<div class="carrier-view-parent p-relative"> <div class="app-link t-upper opensans-regular p-relative">app download link</div> <div class="app-parent p-relative"> <div class="app-download-bar inline-block p-relative bg-color-white">https://protocall.com/app.store/detail?</div> <div class="send-app-bar inline-block p-relative border-all bg-color-green t-caps t-center opensans-regular f-color-w">send app link</div> </div> <div class="settings-click-button clr-fl"> <div class="settings-agency-bar inline-block p-relative bg-color-gray t-caps t-center opensans-regular f-color-w snap">agency</div> <div class="settings-vendor-bar inline-block p-relative bg-color-gray t-caps t-center opensans-regular f-color-w snap">preferred vendors</div> <div class="settings-edit-bar right inline-block p-relative bg-color-green "> <div class="p-relative inline-block"> <div class="edit-icon sprite-im pop-out">&nbsp;</div> </div> <div class="p-relative inline-block t-caps t-right opensans-regular f-color-w">edit</div> </div> </div> <div class="bg-color-white"> <div class="settings-view-leftblock inline-block v-align-mid p-relative"> <div class="settings-view-auth opensans-regular p-relative"> <div class="carrier-view-name inline-block t-caps">agency id</div> <div class="carrier-view-id inline-block">#HP092 542</div> </div> <div class="settings-logo-view p-relative"> <div class="settingslogo-viewpic"> <img src="http://devilsworkshop.org/files/2013/01/enlarged-facebook-profile-picture.jpg" alt="" class="carrier-img-width"> </div> </div> <div class="settings-view-social p-relative clr-fr"> <div class="settings-view-website p-relative left bg-color-green"> <div class="p-relative inline-block v-align-top"> <div class="sprite-im pop-out">&nbsp;</div> </div> <div class="carrier-website-name inline-block t-caps opensans-regular f-color-w t-center">website</div> </div> <div class="settings-view-facebook p-relative left bg-color-green"> <div class="p-relative inline-block v-align-top"> <div class="sprite-im pop-out">&nbsp;</div> </div> <div class="carrier-facebook-name inline-block t-caps opensans-regular f-color-w t-center">facebook</div> </div> </div> </div> <div class="settings-view-rightblock inline-block v-align-mid p-relative "> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">carrier agency id</div> <div class="carrier-left-content t-left right ">#55475546</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">master agency id</div> <div class="carrier-left-content t-left right">#55475546</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">agency type</div> <div class="carrier-left-content t-left right ">master type</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">name</div> <div class="carrier-left-content t-left right">john joe</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl border-bot"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">address</div> <div class="carrier-left-content t-left right ">3951 westere parkway</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">address</div> <div class="carrier-left-content t-left right">478 western gateway</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view border-bot clr-fl"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">city</div> <div class="carrier-left-content t-left right ">california</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">state</div> <div class="carrier-left-content t-left right t-upper">us</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view border-bot clr-fl"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width t-caps opensans-regular clr-fl"> <div class="carrier-left-title t-right left">zip</div> <div class="carrier-left-content t-left right ">9401</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left">phone</div> <div class="carrier-left-content t-left right t-upper">(415)994-00000</div> </div> </div> </div> </div> <div class="carrier-view-block p-relative "> <div class="carrier-border-view clr-fl"> <div class="carrier-view-left p-relative left"> <div class="carrier-left-width opensans-regular clr-fl"> <div class="carrier-left-title t-right left t-caps">email</div> <div class="carrier-left-content t-left right ">agent@mail.com</div> </div> </div> <div class="carrier-view-right right t-caps opensans-regular"> <div class="carrier-left-width clr-fl"> <div class="carrier-left-title t-right left"></div> <div class="carrier-left-content t-left right t-upper"></div> </div> </div> </div> </div> </div></div>';
			return html;
		},
		
		staticMyProfileViewTemplate:function(){
			var html ='<div class="agenyparent-class bg-color-white"> <div class="p-relative"> <div class="agenyleft-profile inline-block v-align-mid p-relative"> <div class="agenyleft-image border-all"> <div class="overflow-hidden"> <div class="agenypic-info"> <img src="./images/images.jpg" alt="" class="ageny-img-width"> </div> <div class="v-align-mid opensans-regular text-color-overlay f-sz-12 p-relative"> <div class="sprite-im calendar-icon inline-block">&nbsp;</div> <div class="t-upper inline-block">Change Image</div> </div> </div> </div> </div> <div class="agenyright-profile inline-block v-align-mid"> <div class="agenyparent-block"> <div class ="agenyinternal-block"> <div class="agenygroup-block border-bot opensans-regular"> <div class="agenychild-block"> <div class="agenytitle-block inline-block p-relative">Name</div> <div class="agenycontent-block inline-block p-relative">James Jeo</div> </div> </div> <div class="agenygroup-block border-bot opensans-regular"> <div class="agenychild-block"> <div class="agenytitle-block inline-block p-relative">Phone</div> <div class="agenycontent-block inline-block p-relative">(415) 994-0000</div> </div> </div> <div class="agenygroup-block border-bot opensans-regular"> <div class="agenychild-block"> <div class="agenytitle-block inline-block p-relative">Email</div> <div class="agenycontent-block inline-block p-relative">james.j@mail.com</div> </div> </div> </div> </div> </div> </div> </div>';
			return html;
		}
	},
	myreps:{
		inviteRepsTemplate:function(){
			var html = '<h2 class="t-left f-color-green opensans-regular" style="">Invite Reps</h2>'
							+'<div class="o-sub-content p-relative">'
								+'<div class="f-sz-14 t-left opensans-regular invite-reps-text">User will have access to all the features of Dashboard</div>'
								+'<div class="text-box-outer">'
									+'<input type="text" class="opensans-regular" placeholder="Mail Address" />'
								+'</div>'
								+'<div class="o-btn snap opensans-regular p-relative t-center bg-color-red f-color-w" data-type="overlaybtn">Done</div>'
							+'</div>';
			return html;
		
		}
	
	}
	
};
